const race_image = {
  Aqua: require('../../images/Aqua.png'),
  'Beast-Warrior': require('../../images/Beast-Warrior.png'),
  Beast: require('../../images/Beast.png'),
  Continuous: require('../../images/Continuous.png'),
  Counter: require('../../images/Counter.png'),
  DARK: require('../../images/DARK.png'),
  Dinosaur: require('../../images/Dinosaur.png'),
  'Divine-Beast': require('../../images/Divine-Beast.png'),
  DIVINE: require('../../images/DIVINE.png'),
  Dragon: require('../../images/Dragon.png'),
  EARTH: require('../../images/EARTH.png'),
  Equip: require('../../images/Equip.png'),
  Fairy: require('../../images/Fairy.png'),
  Field: require('../../images/Field.png'),
  Fiend: require('../../images/Fiend.png'),
  FIRE: require('../../images/FIRE.png'),
  Fish: require('../../images/Fish.png'),
  Insect: require('../../images/Insect.png'),
  LIGHT: require('../../images/LIGHT.png'),
  Machine: require('../../images/Machine.png'),
  Normal: require('../../images/Normal.png'),
  Plant: require('../../images/Plant.png'),
  Psychic: require('../../images/Psychic.png'),
  Pyro: require('../../images/Pyro.png'),
  'Quick-Play': require('../../images/Quick-Play.png'),
  Reptile: require('../../images/Reptile.png'),
  Ritual: require('../../images/Ritual.png'),
  Rock: require('../../images/Rock.png'),
  'Sea Serpent': require('../../images/Sea Serpent.png'),
  Spellcaster: require('../../images/Spellcaster.png'),
  Thunder: require('../../images/Thunder.png'),
  Warrior: require('../../images/Warrior.png'),
  WATER: require('../../images/WATER.png'),
  WIND: require('../../images/WIND.png'),
  'Winged Beast': require('../../images/Winged Beast.png'),
  Wyrm: require('../../images/Wyrm.png'),
  Zombie: require('../../images/Zombie.png'),
};

export default race_image;
